### ISSUE TITLE
Memory corruption bug with stageros

### ISSUE THREAD

**Issue by claudinebadue** [allenh1/p2os#35]
Dear all,

I am trying to simulate a Pioneer robot using the Stage Simulator. For this, I am following the tutorial available at http://wiki.ros.org/p2os-purdue/Tutor... . When I use the command:

roslaunch p2os_launch stage-pioneer-3dx-sick.launch

I get the following error message:

*** Error in `/home/claudine/catkin_ws/devel/lib/stage_ros/stageros': malloc(): memory corruption: 0x000000000178cf90 ***
[stageros-3] process has died [pid 13306, exit code -6, cmd /home/claudine/catkin_ws/devel/lib/stage_ros/stageros /home/claudine/catkin_ws/src/p2os/p2os_launch/launch/stage-worlds/pioneer3dx-sick.world __name:=stageros __log:=/home/claudine/.ros/log/f9f917c4-107a-11e5-bd7c-a417312cfbde/stageros-3.log].
log file: /home/claudine/.ros/log/f9f917c4-107a-11e5-bd7c-a417312cfbde/stageros-3*.log

I am using Ubuntu 14.04 and ROS Indigo.

Ideas of how to solve this problem?

Kind regards,

Claudine

**Comment by progtologist** [comment]
This appears to be a known bug in stageros. Read ros-simulation/stage_ros#21

**Comment by allenh1** [comment]
Is this issue ok to close?

**Comment by progtologist** [comment]
Yes, it's not really an issue of p2os!
