### ISSUE TITLE
p2os_urdf: launch files not working on indigo

### ISSUE THREAD

**Issue by skasperski** [allenh1/p2os#38]
When I try to run 'pioneer3at_urdf.launch' or 'pioneer3dx_urdf.launch', it causes the robot_state_publisher to crash. Might this be an issue with the generated robot_description?

**Comment by allenh1** [comment]
I have not yet had the time to figure this out, but I believe you are on the right track. I will see if I can look at it later today.

**Comment by DavidHan008** [comment]
How can I use it?
