### ISSUE TITLE
p2os_urdf  build failure due to undeclared linking dependency

### ISSUE THREAD

**Issue by tfoote** [allenh1/p2os#39]
p2os_urdf is failing to build now due to missing symbols at link time. It appears to have become a problem due to robot_state_publisher switching to use tf2 from tf and not longer exporting link flags needed for this package. https://github.com/ros/rosdistro/pull/9700

Failed build: http://54.183.26.131:8080/view/Jbin_uU64/job/Jbin_uU64__p2os_urdf__ubuntu_utopic_amd64__binary/9/console
```
00:06:04.972 CMakeFiles/p2os_publisher.dir/src/publisher.cc.o: In function `main':
00:06:04.972 /tmp/binarydeb/ros-jade-p2os-urdf-2.0.2/src/publisher.cc:48: undefined reference to `tf::TransformBroadcaster::TransformBroadcaster()'
00:06:04.973 collect2: error: ld returned 1 exit status
```

I think it just takes adding `tf` to as a `CATKIN_DEPENDS` [here](https://github.com/allenh1/p2os/blob/master/p2os_urdf/CMakeLists.txt#L7)

**Comment by allenh1** [comment]
Hm. Ok. I'll get on that right now.
