### ISSUE TITLE
p2os_urdf regression

### ISSUE THREAD

**Issue by trainman419** [allenh1/p2os#40]
It looks like p2os_urdf suffered some kind of regression and was removed from the ROS build farm back in November: http://lists.ros.org/pipermail/ros-users/2015-November/069765.html

This showed up on ROS Answers: http://answers.ros.org/question/225026/nav2d-installation/ and appears to be preventing users from using the p2os simulator.

I suspect this is related to #39

**Comment by trainman419** [comment]
Also of note, p2os_urdf is no longer listed as a package to build in the rosdistro file for Indigo: https://github.com/ros/rosdistro/blob/0e0924bbd9a89ebda3139883b6f17e17def9b218/indigo/distribution.yaml#L6657-L6677

**Comment by trainman419** [comment]
The failure of p2os_urdf to build was noted here: https://github.com/ros/rosdistro/pull/9733 and a fix and release was requested, but p2os_urdf has not been fixed and released again.

**Comment by allenh1** [comment]
It should be good now. I've re-released for lunar since then and all seems to be fine (passing CI and whatnot).

**Comment by mikaelarguedas** [comment]
@allenh1 now that this package has been re-released on indigo, the note on [the wiki](http://wiki.ros.org/p2os_urdf) about this package being unavailable can be removed

**Comment by allenh1** [comment]
@mikaelarguedas I have updated the note. Thanks!
