### ISSUE TITLE
How to launch it

### ISSUE THREAD

**Issue by grafoteka** [allenh1/p2os#41]
Hi! 
I'm trying to use this package with a Pioneer 3AT with ROS Hydro.

The problem is that I don't know exactly how to move my robot physically. I launch the packages _driver and _teleop_joy.

If I read some topics the joystick is sending values, but my robot doesn't move.

What I'm doing wrong?

Thank you! 
Regards, Jorge

**Comment by allenh1** [comment]
Hm. Did you enable the motors?

```
rostopic pub /cmd_motor_state p2os_driver/MotorState 1
```

Is the easiest way to do it.

**Comment by allenh1** [comment]
There is now a launch file in the driver.

**Comment by grafoteka** [comment]
Thank you @allenh1 it worked with rostopic pub

**Comment by keimura** [comment]
So I'm having the same issue with the motors not enabling...
I used the command 
rostopic pub /cmd_motor_state p2os_msgs/MotorState 1
because when I used the command you suggested above it gave me an invalid eror message type error. But I still don't have any control when launching teleop_keyboard.launch.

**Comment by allenh1** [comment]
@keimura do you have the `p2os_msgs` package installed?

**Comment by keimura** [comment]
If you're talking about the p2os_msgs folder that was part of the master branch then yes. I hope what I said made sense...

**Comment by allenh1** [comment]
Are you running an Ubuntu system? Because you can always just apt-get install it.

```
$ sudo apt-get install ros-lunar-p2os*
```

(I just want to eliminate any environment problems before we look down other avenues).

**Comment by keimura** [comment]
I'm sorry it turns out it was a hardware issue with the pioneer I was using. The code works beautifully.

Thank you for the quick replys

**Comment by allenh1** [comment]
Glad to hear it! I can close this then?

**Comment by allenh1** [comment]
Wait -- nevermind... XD
