### ISSUE TITLE
Releasing a debinc on lunar

### ISSUE THREAD

**Issue by mikaelarguedas** [allenh1/p2os#47]
Now that compilation is [fixed](https://github.com/allenh1/p2os/commit/5f328a4aca386e5f43d7a23423a681c248012b25) on newer platforms :tada: is it possible to make a debinc release to propagate the change to the buildfarm ?
You can directly run `bloom-release -r lunar -t lunar` without bumping the version number

**Comment by allenh1** [comment]
Will do, unfortunately I can't do this until Tuesday because bloom does not work on Gentoo...

**Comment by allenh1** [comment]
Fixed: ros/rosdistro#15112.
