### ISSUE TITLE
[question] use of collada_urdf.cpp and dependency on tinyxml

### ISSUE THREAD

**Issue by mikaelarguedas** [allenh1/p2os#49]
I was just wondering what is the use of [collada_urdf.cpp](https://github.com/allenh1/p2os/blob/master/p2os_urdf/models/collada_urdf.cpp) in this repository. I came across this by tracking down packages downstream of pluginlib that use tinyxml symbols without depending on it.

**Comment by allenh1** [comment]
lol -- what is that file??? Is that HTML? Ok -- gonna kill that with fire XD

**Comment by mikaelarguedas** [comment]
haha yeah that was my understanding as well ^^ looks like a wget on a page that displays code and not the raw version of the file o_O

**Comment by allenh1** [comment]
Ya, I can see a 16-year-old me doing that. Thanks for noticing! Otherwise, it probably never would have left.
