### ISSUE TITLE
Pioneer3-DX controller design 

### ISSUE THREAD

**Issue by yjkim9278** [allenh1/p2os#66]
Hi,
I'm trying to design my own controller and I have simulated in Gazebo and it works perfectly fine. However when i'm trying to implement the controller to the P3DX it goes to unstable. So I was wondering, whether your p2os package has inbuilt controller already, if so is it possible to by pass the internal controller?

**Comment by allenh1** [comment]
> however when i'm trying to implement the controller to the P3DX

Could you please clarify what you mean by "controller" here? In particular, which ROS topics are you expecting to exist / which ones are not functioning as you are expecting?

**Comment by yjkim9278** [comment]
Sorry for the misunderstanding. 
So I have designed a linear controller based on the kinematics of the robot. And the controller controls both linear and angular velocity of the robot.  
Every-time when I run p2os_deriver.launch file, it said "Started with pid", so assume that it has internal PID which tracks the commanded linear and angular velocity.  
I want to bypass that PID controller such that my controller can take it over and track the references velocity profiles.

**Comment by allenh1** [comment]
> it said "Started with pid", so assume that it has internal PID which tracks the commanded linear and angular velocity.

I think I see the confusion here... PID in this case means "Process ID". Let me know if you have any other questions.
